version: "3"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - dock_net
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  backend:
    depends_on:
      - mongo
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - dock_net
    environment:
      MONGODB_URL: mongodb://root:example@mongo:27017/
  frontend:
    depends_on:
      - backend
    container_name: frontend
    links:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - dock_net
    environment:
      BACK_URL: http://backend:5000
networks:
  dock_net:
    driver: bridge